apiVersion: apps/v1
kind: Deployment
metadata:
  name: imersao-fullcycle-3-desafio-3-api
spec:
  selector:
    matchLabels:
      app: imersao-fullcycle-3-desafio-3-api
  template:
    metadata:
      labels:
        app: imersao-fullcycle-3-desafio-3-api
    spec:
      containers:
        - name: imersao-fullcycle-3-desafio-3-api
          image: stachovski/imersao-fullcycle-3-desafio-3-api:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
          - name: "TYPEORM_CONNECTION"
            value: "postgres"
          - name: "TYPEORM_HOST"
            value: "imersao-fullcycle-3-desafio-3-db"
          - name: "TYPEORM_USERNAME"
            value: "postgres"
          - name: "TYPEORM_PASSWORD"
            value: "root"
          - name: "TYPEORM_DATABASE"
            value: "db"
          - name: "TYPEORM_PORT"
            value: "5432"
          - name: "TYPEORM_ENTITIES"
            value: "dist/**/*.entity.js"
          - name: "TYPEORM_ENTITIES_DIR"
            value: "src"
          - name: "TYPEORM_MIGRATIONS"
            value: "src/migrations/*.ts"
          - name: "TYPEORM_MIGRATIONS_DIR"
            value: "src/migrations"