apiVersion: apps/v1
kind: Deployment
metadata:
  name: imersao-fullcycle-3-desafio-3-api-db
spec:
  selector:
    matchLabels:
      app: imersao-fullcycle-3-desafio-3-api-db
  template:
    metadata:
      labels:
        app: imersao-fullcycle-3-desafio-3-api-db
    spec:
      containers:
        - name: imersao-fullcycle-3-desafio-3-api-db
          image: postgres:13
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: imersao-fullcycle-3-desafio-3-api-db
          envFrom:
          - configMapRef:
              name: imersao-fullcycle-3-desafio-3-api-db-config
      volumes:
        - name: imersao-fullcycle-3-desafio-3-api-db
          persistentVolumeClaim:
            claimName: imersao-fullcycle-3-desafio-3-api-db-pvc